server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}
      
#SECRET KEY
jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M
jasypt:
  encryptor:
    password: aflkkey
token:
  access-expired-time : 3600000
  refresh-expired-time : 3600000

spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'       
  cloud:
    gateway:
      routes:
        - id: auth # 구분하기 위한 id값으로 임의로 작성해도 무관
          predicates: # auth/ 으로 요청이 들어오면
            - Path=/auth/**
          uri: lb://auth # 유레카 서버에서 auth를 찾아서 그곳으로 요청을 보낸다.
          filters:
            # url 재정의
            # ?<변수명>은 뒤에 나오는 정규식을 변수처럼 사용할 수 있도록 한다. ()는 하나의 묶음 처리 -> segment는 (.*)를 의미
            # 콤마(,)를 기준으로 왼쪽 url을 오른쪽 url로 재정의한다.
            # 콤마 기준 오른쪽 부분은 ${변수명}으로 url 가져오고 앞에 / 붙여준거라고 보면 된다.
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        # user/swagger 시작
        - id: user
          predicates:
            - Path=/user/swagger/**
          uri: lb://user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            
        - id: user
          predicates:
            - Path=/user/swagger-ui/**
          uri: lb://user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            
        - id: user
          predicates:
            - Path=/user/swagger-resources/**
          uri: lb://user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            
        - id: user
          predicates:
            - Path=/user/v2/**
          uri: lb://user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        # user/swagger 끝
        
        # user/signup --회원가입
        - id: user
          predicates:
            - Path=/user/signup
            - Method=POST
          uri: lb://user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        # user/login --로그인
        - id: user
          predicates:
            - Path=/user/login
            - Method=POST
          uri: lb://user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        # user/** --
        - id: user
          predicates:
            - Path=/user/**
            - Method=GET
          uri: lb://user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter # JWT 검증을 위한 Custom GatewayFilter