server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}

logging:
  level:
    org.springframework.cloud.gateway: warn

#SECRET KEY
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
token:
  access-expired-time : 3600000
  refresh-expired-time : 3600000

spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${CLIENT_URL}
              - ${CLIENT_URL_LOCAL}
              - ${CLIENT_URL_LOCAL1}
              - ${CLIENT_URL_LOCAL2}
              - ${CLIENT_URL_LOCAL3}
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: auth
          predicates:
            - Path=/auth/**
          uri: lb://auth
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: socket-streamer
          predicates:
            - Path=/ws-stomp/**
            - Method=GET,OPTIONS,POST
          uri: lb://socket-streamer
          filters:
            - RewritePath=/ws-stomp/(?<segment>.*), /$\{segment}
            - SetPath=/ws-stomp/**

        # user/swagger 시작
        - id: user
          predicates:
            - Path=/user/swagger/**
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user
          predicates:
            - Path=/user/swagger-ui/**
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user
          predicates:
            - Path=/user/swagger-resources/**
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user
          predicates:
            - Path=/user/v2/**
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        # user/swagger 끝

        - id: user-signup
          predicates:
            - Path=/user/signup
            - Method=POST,OPTIONS
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user-login
          predicates:
            - Path=/user/login
            - Method=POST,OPTIONS
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user
          predicates:
            - Path=/user/me
            - Method=GET
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter