server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}

logging:
  level:
    org.springframework.cloud.gateway: warn

#SECRET KEY
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
token:
  access-expired-time : 3600000
  refresh-expired-time : 3600000

spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${CLIENT_URL}
              - ${CLIENT_URL_LOCAL}
              - ${CLIENT_URL_LOCAL1}
              - ${CLIENT_URL_LOCAL2}
              - ${CLIENT_URL_LOCAL3}
              - ${CLIENT_URL_LOCAL4}
              - ${CLIENT_URL_LOCAL5}
              - ${CLIENT_URL_LOCAL6}
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        # user/swagger 시작
        - id: user-swagger
          predicates:
            - Path=/user/swagger/**,/user/swagger-ui/**,/user/swagger-resources/**,/user/v2/**
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        # user/swagger 끝

        # chat/swagger 시작
        - id: chat-swagger
          predicates:
            - Path=/chat/swagger/**,/chat/swagger-ui/**,/chat/swagger-resources/**,/chat/v2/**
          uri: lb://chat
          filters:
            - RewritePath=/chat/(?<segment>.*), /$\{segment}
        # chat/swagger 끝

        # ai-connector/swagger 시작
        - id: ai-connector-swagger
          predicates:
            - Path=/ai-connector/swagger/**,/ai-connector/swagger-ui/**,/ai-connector/swagger-resources/**,/ai-connector/v2/**
          uri: lb://ai-connector
          filters:
            - RewritePath=/ai-connector/(?<segment>.*), /$\{segment}
        # ai-connector/swagger 끝

        # file_storage/swagger 시작
        - id: file-storage-swagger
          predicates:
            - Path=/file-storage/swagger/**,/file-storage/swagger-ui/**,/file-storage/swagger-resources/**,/file-storage/v2/**
          uri: lb://file-storage
          filters:
            - RewritePath=/file-storage/(?<segment>.*), /$\{segment}
        # file_storage/swagger 끝

        # trade/swagger 시작
        - id: trade-swagger
          predicates:
            - Path=/trade/swagger/**,/trade/swagger-ui/**,/trade/swagger-resources/**,/trade/v2/**
          uri: lb://trade
          filters:
            - RewritePath=/trade/(?<segment>.*), /$\{segment}
        # trade/swagger 끝

        - id: socket-streamer
          predicates:
            - Path=/socket-streamer/**
            - Method=GET,OPTIONS,POST
          uri: lb://socket-streamer
          filters:
            - RewritePath=/socket-streamer/(?<segment>.*), /$\{segment}
          #  - SetPath=/ws-stomp/**

        - id: user-signup
          predicates:
            - Path=/user/signup
            - Method=POST,OPTIONS
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user-login
          predicates:
            - Path=/user/login,/user/login/refresh
            - Method=POST,OPTIONS
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user
          predicates:
            - Path=/user/me,/user/userInfo,/user/users,/user/grid
            - Method=OPTIONS,POST,PUT,GET,DELETE
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: chat
          predicates:
            - Path=/chat/**
            - Method=OPTIONS,POST,PUT,GET,DELETE
          uri: lb://chat
          filters:
            - RewritePath=/chat/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: ai-connector
          predicates:
            - Path=/ai-connector/**
            - Method=OPTIONS,POST,GET
          uri: lb://ai-connector
          filters:
            - RewritePath=/ai-connector/(?<segment>.*), /$\{segment}

        - id: trade
          predicates:
            - Path=/trade/**
            - Method=OPTIONS,POST,GET
          uri: lb://trade
          filters:
            - RewritePath=/trade/(?<segment>.*), /$\{segment}

        - id: pal
          predicates:
            - Path=/pal/**
            - Method=OPTIONS,POST,GET
          uri: lb://pal
          filters:
            - RewritePath=/pal/(?<segment>.*), /$\{segment}

        - id: nutritionist
          predicates:
            - Path=/nutritionist/**
            - Method=OPTIONS,POST,GET
          uri: lb://nutritionist
          filters:
            - RewritePath=/nutritionist/(?<segment>.*), /$\{segment}

        - id: file-storage
          predicates:
            - Path=/file-storage/display
            - Method=OPTIONS,POST,GET
          uri: lb://file-storage
          filters:
            - RewritePath=/file-storage/(?<segment>.*), /$\{segment}

        - id: file-storage
          predicates:
            - Path=/file-storage/upload
            - Method=OPTIONS,POST,GET
          uri: lb://file-storage
          filters:
            - RewritePath=/file-storage/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: file-storage
          predicates:
            - Path=/file-storage/delete
            - Method=OPTIONS,DELETE
          uri: lb://file-storage
          filters:
            - RewritePath=/file-storage/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter