server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}

logging:
  level:
    org.springframework.cloud.gateway: warn

#SECRET KEY
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
token:
  access-expired-time : 3600000
  refresh-expired-time : 3600000

spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${CLIENT_URL}
              - ${CLIENT_URL_LOCAL}
              - ${CLIENT_URL_LOCAL1}
              - ${CLIENT_URL_LOCAL2}
              - ${CLIENT_URL_LOCAL3}
              - ${CLIENT_URL_LOCAL4}
              - ${CLIENT_URL_LOCAL5}
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        # user/swagger 시작
        - id: user-swagger
          predicates:
            - Path=/user/swagger/**,/user/swagger-ui/**,/user/swagger-resources/**,/user/v2/**
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        # user/swagger 끝

        # chat/swagger 시작
        - id: chat-swagger
          predicates:
            - Path=/chat/swagger/**,/chat/swagger-ui/**,/chat/swagger-resources/**,/chat/v2/**
          uri: lb://chat
          filters:
            - RewritePath=/chat/(?<segment>.*), /$\{segment}
        # chat/swagger 끝

        # file_storage/swagger 시작
        - id: file-storage-swagger
          predicates:
            - Path=/file-storage/swagger/**,/file-storage/swagger-ui/**,/file-storage/swagger-resources/**,/file-storage/v2/**
          uri: lb://file-storage
          filters:
            - RewritePath=/file-storage/(?<segment>.*), /$\{segment}
        # file_storage/swagger 끝

        - id: socket-streamer
          predicates:
            - Path=/socket-streamer/**
            - Method=GET,OPTIONS,POST
          uri: lb://socket-streamer
          filters:
            - RewritePath=/socket-streamer/(?<segment>.*), /$\{segment}
          #  - SetPath=/ws-stomp/**

        - id: user-signup
          predicates:
            - Path=/user/signup
            - Method=POST,OPTIONS
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user-login
          predicates:
            - Path=/user/login
            - Method=POST,OPTIONS
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user
          predicates:
            - Path=/user/me
            - Method=OPTIONS,POST,GET
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: user
          predicates:
            - Path=/user/userInfo
            - Method=OPTIONS,POST
          uri: lb://user
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: chat
          predicates:
            - Path=/chat/**
            - Method=OPTIONS,POST,GET
          uri: lb://chat
          filters:
            - RewritePath=/chat/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: file-storage
          predicates:
            - Path=/file-storage/**
            - Method=OPTIONS,POST,GET
          uri: lb://file-storage
          filters:
            - RewritePath=/file-storage/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter